version: '3.1'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 123456

  mysqldb:
    hostname: mysqldb
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    hostname: redis
    container_name: "redis_server"
    image: redis:latest
    restart: on-failure
    command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - 6379:6379